[package]
name = "Quantum-Lending-Platform"
version = "0.1.0"

[dependencies]
anchor-lang = "0.17.0"
solana-program = "1.7.0"


[dev-dependencies]
solana-sdk = "2.0.10"
solana-program-test = "2.0.10"


[features]
idl-build = ["anchor-lang/idl-build"]